// provincias_cuba.dart
//
// Lista de las 16 provincias de Cuba + el municipio especial Isla de
// la Juventud. Cada provincia tiene su lista completa de municipios,
// que el Paso 3 del stepper muestra como dropdown.

const List<String> kProvinciasCuba = [
  'Pinar del Río',
  'Artemisa',
  'La Habana',
  'Mayabeque',
  'Matanzas',
  'Cienfuegos',
  'Villa Clara',
  'Sancti Spíritus',
  'Ciego de Ávila',
  'Camagüey',
  'Las Tunas',
  'Holguín',
  'Granma',
  'Santiago de Cuba',
  'Guantánamo',
  'Isla de la Juventud',
];

/// Provincias que tienen su lista de municipios cargada -- todas.
const Map<String, List<String>> kMunicipiosPorProvincia = {
  'Pinar del Río': [
    'Pinar del Río',
    'San Juan y Martínez',
    'San Luis',
    'Consolación del Sur',
    'Los Palacios',
    'Minas de Matahambre',
    'Viñales',
    'La Palma',
    'Bahía Honda',
    'Candelaria',
    'San Cristóbal',
    'Guane',
    'Mantua',
    'Sandino',
  ],
  'Artemisa': [
    'Artemisa',
    'Alquízar',
    'Bauta',
    'Caimito',
    'Guanajay',
    'Güira de Melena',
    'Mariel',
    'San Antonio de los Baños',
    'Cabañas',
    'Bahía Honda',
    'San Cristóbal',
    'Candelaria',
  ],
  'La Habana': [
    'Playa',
    'Plaza de la Revolución',
    'Centro Habana',
    'Habana Vieja',
    'Regla',
    'Habana del Este',
    'Guanabacoa',
    'San Miguel del Padrón',
    'Diez de Octubre',
    'Cerro',
    'Marianao',
    'La Lisa',
    'Boyeros',
    'Arroyo Naranjo',
    'Cotorro',
  ],
  'Mayabeque': [
    'San José de las Lajas',
    'Güines',
    'Melena del Sur',
    'Batabanó',
    'Quivicán',
    'Bejucal',
    'Santa Cruz del Norte',
    'Jaruco',
    'Madruga',
    'Nueva Paz',
    'San Nicolás de Bari',
    'Güira de Melena',
  ],
  'Matanzas': [
    'Matanzas',
    'Cárdenas',
    'Colón',
    'Jagüey Grande',
    'Jovellanos',
    'Pedro Betancourt',
    'Limónar',
    'Los Arabos',
    'Martí',
    'Perico',
    'Unión de Reyes',
    'Calimete',
    'Ciénaga de Zapata',
    'Varadero',
  ],
  'Cienfuegos': [
    'Cienfuegos',
    'Abreus',
    'Aguada de Pasajeros',
    'Cruces',
    'Cumanayagua',
    'Lajas',
    'Palmira',
    'Rodas',
    'Santa Isabel de las Lajas',
  ],
  'Villa Clara': [
    'Santa Clara',
    'Camajuaní',
    'Caibarién',
    'Encrucijada',
    'Manicaragua',
    'Placetas',
    'Quemado de Güines',
    'Ranchuelo',
    'Remedios',
    'Sagua la Grande',
    'Santo Domingo',
    'Cifuentes',
    'Corralillo',
  ],
  'Sancti Spíritus': [
    'Sancti Spíritus',
    'Trinidad',
    'Yaguajay',
    'Jatibonico',
    'Taguasco',
    'Cabaiguán',
    'Fomento',
    'La Sierpe',
  ],
  'Ciego de Ávila': [
    'Ciego de Ávila',
    'Morón',
    'Florencia',
    'Chambas',
    'Primero de Enero',
    'Bolivia',
    'Venezuela',
    'Baraguá',
    'Majagua',
    'Ciro Redondo',
    'Ceballos',
  ],
  'Camagüey': [
    'Camagüey',
    'Nuevitas',
    'Guáimaro',
    'Sibanicú',
    'Esmeralda',
    'Florida',
    'Vertientes',
    'Jimaguayú',
    'Najasa',
    'Santa Cruz del Sur',
    'Minas',
    'Sierra de Cubitas',
    'Carlos Manuel de Céspedes',
  ],
  'Las Tunas': [
    'Victoria de Las Tunas',
    'Puerto Padre',
    'Jesús Menéndez',
    'Majibacoa',
    'Jobabo',
    'Colombia',
    'Amancio',
    'Manatí',
  ],
  'Holguín': [
    'Holguín',
    'Banes',
    'Antilla',
    'Báguanos',
    'Cacocum',
    'Calixto García',
    'Cueto',
    'Frank País',
    'Gibara',
    'Mayarí',
    'Moa',
    'Rafael Freyre',
    'Sagua de Tánamo',
    'Urbano Noris',
    'Guardalavaca',
  ],
  'Granma': [
    'Bayamo',
    'Manzanillo',
    'Jiguaní',
    'Yara',
    'Bartolomé Masó',
    'Buey Arriba',
    'Cauto Cristo',
    'Campechuela',
    'Guisa',
    'Media Luna',
    'Niquero',
    'Pilón',
    'Río Cauto',
    'Calixto García',
  ],
  'Santiago de Cuba': [
    'Santiago de Cuba',
    'Contramaestre',
    'Mella',
    'San Luis',
    'Songo-La Maya',
    'Segundo Frente',
    'Tercer Frente',
    'Palmira',
    'Guamá',
    'Niceto Pérez',
  ],
  'Guantánamo': [
    'Guantánamo',
    'Baracoa',
    'Maisí',
    'Imías',
    'San Antonio del Sur',
    'Caimanera',
    'Manuel Tames',
    'Yateras',
    'El Salvador',
    'Niceto Pérez',
  ],
  'Isla de la Juventud': [
    'Nueva Gerona',
    'La Fe',
    'Santa Fe',
    'Cocodrilo',
  ],
};

/// true si esta provincia ya tiene municipios cargados (dropdown);
/// false si todavía debe pedirse como texto libre.
bool tieneMunicipiosCargados(String provincia) =>
    kMunicipiosPorProvincia.containsKey(provincia);

List<String> municipiosDe(String provincia) =>
    kMunicipiosPorProvincia[provincia] ?? const [];
